name: Build & Test MSHV Crate
on: 
  pull_request:

jobs:
  infra-setup:
    name: MSHV Infra Setup
    uses: ./.github/workflows/mshv-infra.yaml
    with:
      ARCH: x86_64
      OS_DISK_SIZE: 512
      RG: MSHV-${{ github.run_id }}
      SKU: Standard_D16s_v5
    secrets:
      MI_CLIENT_ID: ${{ secrets.MSHV_MI_CLIENT_ID }}
      RUNNER_RG: ${{ secrets.MSHV_RUNNER_RG }}
      RUNNER: ${{ secrets.MSHV_RUNNER }}
      STORAGE_ACCOUNT_PATHS: ${{ secrets.MSHV_STORAGE_ACCOUNT_PATHS }}
      X86_SOURCE_PATH: ${{ secrets.MSHV_X86_SOURCE_PATH }}
      USERNAME: ${{ secrets.MSHV_USERNAME }}

  build-test:
    name: Build & test
    needs: infra-setup
    if: ${{ always() && needs.infra-setup.result == 'success' }}
    runs-on:
      - self-hosted
      - Linux
    steps:
      - name: Build & Run tests on remote VM
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PRIVATE_IP: ${{ needs.infra-setup.outputs.PRIVATE_IP }}
          RG: MSHV-${{ github.run_id }}
          USERNAME: ${{ secrets.MSHV_USERNAME }}
        run: |
          set -e
          echo "Connecting to the VM via SSH..."
          ssh -i ~/.ssh/azure_key -o StrictHostKeyChecking=no ${USERNAME}@${PRIVATE_IP} << EOF
            set -e
            echo "Logged in successfully."
            export PATH="\$HOME/.cargo/bin:\$PATH"
            cd mshv
            git fetch origin pull/${PR_NUMBER}/merge
            git checkout FETCH_HEAD
            cargo build --all-features --workspace
            cargo test --all-features --workspace
          EOF
          echo "Build and test completed successfully."

  cleanup:
    name: Cleanup
    needs: build-test
    if: always()
    runs-on:
      - self-hosted
      - Linux
    steps:
      - name: Delete RG
        run: |
          if az group exists --name MSHV-${{ github.run_id }}; then
            az group delete --name MSHV-${{ github.run_id }} --yes --no-wait
          else
            echo "Resource Group MSHV-${{ github.run_id }} does not exist. Skipping deletion."
          fi
          echo "Cleanup process completed."