name: Build & Test MSHV Crate
on: 
  pull_request:
  workflow_dispatch:
jobs:
  infra-setup:
    name: MSHV Infra Setup
    uses: ./.github/workflows/mshv-infra.yaml
    with:
      ARCH: x86_64
      OS_DISK_SIZE: 512
      RG: MSHV-${{ github.run_id }}
      SSH_KEY: ~/.ssh/azure_key_${{ github.run_id }}_${{ github.workflow_sha }}
      VM_SKU: Standard_D16s_v5
    secrets:
      KEY_VAULT: ${{ secrets.MSHV_KV}}
      PRIVATE_KEY: ${{ secrets.MSHV_PRIVATE_KEY }}
      PUBLIC_KEY: ${{ secrets.MSHV_PUBLIC_KEY }}
      MI_CLIENT_ID: ${{ secrets.MSHV_MI_CLIENT_ID }}
      RUNNER_RG: ${{ secrets.MSHV_RUNNER_RG }}
      RUNNER: ${{ secrets.MSHV_RUNNER }}
      STORAGE_ACCOUNT_PATHS: ${{ secrets.MSHV_STORAGE_ACCOUNT_PATHS }}
      X86_SOURCE_PATH: ${{ secrets.MSHV_X86_SOURCE_PATH }}
      USERNAME: ${{ secrets.MSHV_USERNAME }}

  build-test:
    name: Build & test
    needs: infra-setup
    if: ${{ always() && needs.infra-setup.result == 'success' }}
    runs-on:
      - self-hosted
      - Linux
    steps:
      - name: Build & Run tests on remote VM
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PRIVATE_IP: ${{ needs.infra-setup.outputs.PRIVATE_IP }}
          RG: MSHV-${{ github.run_id }}
          SSH_KEY_NAME: azure_key_${{ github.run_id }}_${{ github.workflow_sha }}
          USERNAME: ${{ secrets.MSHV_USERNAME }}
        run: |
          set -e
          echo "Connecting to the VM via SSH..."
          ssh -i ~/.ssh/${SSH_KEY_NAME} -o StrictHostKeyChecking=no ${USERNAME}@${PRIVATE_IP} << EOF
            set -e
            echo "Logged in successfully."
            export PATH="\$HOME/.cargo/bin:\$PATH"
            cd mshv
            # conditional on pr etc
            cargo build --all-features --workspace
            cargo test --all-features --workspace
          EOF
          echo "Build and test completed successfully."

  cleanup:
    name: Cleanup
    needs: build-test
    if: always()
    runs-on:
      - self-hosted
      - Linux
    steps:
      - name: Delete RG
        env:
          RG: MSHV-${{ github.run_id }}
        run: |
          if az group exists --name ${RG}; then
            az group delete --name ${RG} --yes --no-wait
          else
            echo "Resource Group ${RG} does not exist. Skipping deletion."
          fi
          echo "Cleanup process completed."

      - name: Delete SSH Key
        env:
          SSH_KEY: ~/.ssh/azure_key_${{ github.run_id }}_${{ github.workflow_sha }}
        run: |
          echo "::add-mask::$SSH_KEY"
          if [[ -f ${SSH_KEY} ]]; then
            rm -f ${SSH_KEY} ${SSH_KEY}.pub
            echo "SSH key '${SSH_KEY}' deleted successfully."
          else
            echo "SSH key not found. Nothing to delete."
          fi
